name: Pull Artifacts and SCP to Azure VM

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an appropriate runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Download Artifacts from JFrog
        run: |
          # Use JFrog CLI to download artifacts
          # Example command: jfrog rt dl <source> <destination> --server-id=<server-id>
          # Replace placeholders with actual values
          # Set JFrog credentials using secrets
          echo "Downloading artifacts from JFrog"

      - name: Transfer Artifacts to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_SSH_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: /path/to/artifacts  # Update with your source directory
          target: /path/on/azure/vm  # Update with the target directory on VM

      # Add any additional steps if needed
